repair script msg on fail

diff --git a/reqkit b/reqkit
--- a/reqkit
+++ b/reqkit
@@ -29,7 +29,7 @@ BMC_BOUND=10
 ALPHA=30
 BETA=10
 RTC_MODE=1 # Pono-rt's rtc algorithm: 0 or 1
-REPAIRALGORITHM=min-instant
+REPAIRALGORITHM=instant
 LTL_FORMULA=true
 
 DisplayError()
@@ -57,9 +57,10 @@ Help()
    echo "--delay-first         Timed automata semantics where a single atomic transition is a delay + discrete transition; when false, an atomic transition is a discrete transition + delay (default: $DELAY_FIRST)"
    echo "--bmc-bound           Bound up to which bounded model checking is to be performed (default: $BMC_BOUND)."
    echo "--repair-algorithm    Algorithm to be used for repair: min-instant | instant | generate | modify | instant (default: $REPAIRALGORITHM)"
-   echo "--alpha ALPHA         Replace all constants above ALPHA by infinity (default: $ALPHA); only for the nusmv engine."
-   echo "--beta BETA           The other constant beta from Reiya's script (default: $BETA); only for the nusmv engine."
-   echo "--formula FORMULA     LTL formula to be checked with the ltl analysis."
+   echo "--rtc-mode            Treatment of consistency formulas in Pono-RT: quantifier elimiation (0), or quantified formulas (1) (default: 0)."
+  #  echo "--alpha ALPHA         Replace all constants above ALPHA by infinity (default: $ALPHA); only for the nusmv engine."
+  #  echo "--beta BETA           The other constant beta from Reiya's script (default: $BETA); only for the nusmv engine."
+   echo "--formula FORMULA     Formula to be checked with the ltl or ctl analyses."
    echo "-v                    Verbose mode: show executed instructions."
    echo "-h                    Print help."
    echo
@@ -113,6 +114,14 @@ while getopts ${OPTSTRING} opt; do
                   Help
                 fi
                 ALGORITHM=$val
+                ;;
+            repair-algorithm)
+                val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
+                REPAIRALGORITHM=$val
+                if [ "$ALGORITHM" != "generate" ] && [ "$ALGORITHM" != "modify" ] && [ "$ALGORITHM" != "instant" ] && [ "$ALGORITHM" != "min-instant" ]; then
+                  DisplayError "Invalid algorithm."
+                  Help
+                fi
                 ;;
             bmc-bound)
                 val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
@@ -220,9 +229,6 @@ function generate_sup {
   extension="${basename##*.}"
   basename_noext="${basename%.*}"
 
-  echo $basename
-  echo $extension
-
   if [ "${extension}" = "py" ]; then
     VC_SUP_FILE=$FILE
   elif [ "${extension}" = "sup" ]; then
@@ -231,7 +237,8 @@ function generate_sup {
   else
     VC_SUP_FILE=${OUTPUT_DIR}/$basename_noext".py"
     ${TRANSLATOR_EXEC} --output-fmt sup --input ${FILE} --bool-only-predicates true > ${VC_SUP_FILE}    
-  fi  
+  fi
+  VC_SUP_FILE=`realpath $VC_SUP_FILE`
 }
 
 function repair_sup {
@@ -245,10 +252,11 @@ function repair_sup {
   elif [ "${REPAIRALGORITHM}" = "generate" ]; then
     exec=reqgen.py
   else
-    DisplayError "Unknown repair algorithm"
+    DisplayError "Unknown repair algorithm '$REPAIRALGORITHM'"
     exit -1
   fi
-  python $REPAIR_DIR/$exec $VC_SUP_FILE
+  cd $REPAIR_DIR
+  python $exec $VC_SUP_FILE
 }
 
 function check_rtc_smv {
@@ -275,17 +283,17 @@ function check_rtc_smv {
 function check_vacuity {
     DisplayInfo "Running vacuity analysis with the Pono-RT engine"
     generate_vmt
-    if ! command -v pono &> /dev/null
+    if ! command -v pono-rt &> /dev/null
     then
-        echo "pono could not be found"
+        echo "pono-rt could not be found"
         exit 1
     fi
     external_interpolator=
     if [ "$ALGORITHM" = "ic3ia" ]; then
       external_interpolator="--external-interpolator opensmt"
     fi
-    set +e # This is to avoid the script to exit if pono returns 1
-    pono --smt-solver cvc5 --delay-first $DELAY_FIRST --strict-delays $STRICT_DELAYS $external_interpolator -e $ALGORITHM -k $BMC_BOUND -ta -p 1 --witness ${VC_VMT_FILE} > ${TMP_OUTPUT_FILE}
+    set +e # This is to avoid the script to exit if pono-rt returns 1
+    pono-rt --smt-solver cvc5 --delay-first $DELAY_FIRST --strict-delays $STRICT_DELAYS $external_interpolator -e $ALGORITHM -k $BMC_BOUND -ta -p 1 --witness ${VC_VMT_FILE} > ${TMP_OUTPUT_FILE}
     ret_value=$?
     python3 scripts/parse_pono.py < ${TMP_OUTPUT_FILE}
     if [ $ret_value = 0 ]; then
@@ -301,9 +309,9 @@ function check_rtc {
     DisplayInfo "Running rt-consistency analysis with the Pono-RT engine"
     REQIDS=
     generate_vmt
-    if ! command -v pono &> /dev/null
+    if ! command -v pono-rt &> /dev/null
     then
-        echo "pono could not be found"
+        echo "pono-rt could not be found"
         exit 1
     fi
     external_interpolator=
@@ -311,12 +319,12 @@ function check_rtc {
       external_interpolator="--external-interpolator opensmt"
       RTC_MODE=0
     fi
-    set +e # This is to avoid the script to exit if pono returns 1
+    set +e # This is to avoid the script to exit if pono-rt returns 1
     ta=-ta
     if [ "${TIMEDOMAIN}" = "unit" ]; then
       ta=-ta-unit
     fi
-    pono --smt-solver cvc5 --rt-consistency $RTC_MODE --delay-first $DELAY_FIRST --strict-delays $STRICT_DELAYS $external_interpolator -e $ALGORITHM -k $BMC_BOUND $ta --witness ${VC_VMT_FILE} > ${TMP_OUTPUT_FILE}
+    pono-rt --smt-solver cvc5 --rt-consistency $RTC_MODE --delay-first $DELAY_FIRST --strict-delays $STRICT_DELAYS $external_interpolator -e $ALGORITHM -k $BMC_BOUND $ta --witness ${VC_VMT_FILE} > ${TMP_OUTPUT_FILE}
     ret_value=$?
     python3 scripts/parse_pono.py < ${TMP_OUTPUT_FILE}
     if [ $ret_value = 1 ]; then
